FROM hub.agcs.agetic.gob.bo/dockerhub-proxy/library/node:20-alpine AS base
WORKDIR /home/node/app

RUN mkdir -p node_modules && \
    chown -R node:node /home/node

COPY --chown=node:node package*.json ./

USER node

RUN npm set registry https://registry.agcs.agetic.gob.bo/ && \
    npm set strict-ssl false
    
RUN npm ci --prefer-offline --progress=false --no-audit 

FROM base AS setup
COPY --chown=node:node . .
USER root
RUN apk add --no-cache jq
RUN jq -r '.data.data' secrets.json > secrets_temp.json && \
    jq -r 'to_entries | .[] | "\(.key)=\(.value)"' secrets_temp.json > .env && \
    chown -R node:node .env
USER node
RUN npm run setup
