FROM hub.agcs.agetic.gob.bo/dockerhub-proxy/library/node:20-alpine AS base
WORKDIR /home/node/app

RUN mkdir -p node_modules && \
    chown -R node:node /home/node

COPY --chown=node:node package*.json ./

USER node

RUN npm set registry https://registry.agcs.agetic.gob.bo/ && \
    npm set strict-ssl false
    
RUN npm ci --prefer-offline --progress=false --no-audit 

FROM base AS merge
COPY --chown=node:node . .
RUN npm run format-check
RUN npm run build-docker
